# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               WFU Business Analytics R Programming Guide
tagline:             ''
description:         '<img src="https://raw.githubusercontent.com/wfu-r/wfu-r.github.io/master/public/wfu_logo.png" height=60 </img>  </a>'
url:                 http://wfu-r.github.io
baseurl:             ''

